name: Deploy to S3 
on:
  push:
    branches:
      - main
    paths-ignore: # Ignore changes to files that are not relevant to the deploy actio
      - ".github/workflows/s3.yml"
      - "README.md"
      - "LICENSE"
      - "Dockerfile"
      - "*.txt" # Ignore text files
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude ".*" --exclude "Dockerfile" --exclude "*.txt"