name: CI/CD Pipeline to Deploy Static Website to S3

# Add permissions for the entire workflow
permissions:
  contents: read
  security-events: write
  pull-requests: read

on:
  push:
    branches:
     - main
    paths-ignore:
      - 'README.md'
    
  pull_request:
    branches:
      - dependabot/**

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Dependabot
        uses: dependabot/fetch-metadata@v1
        if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  deploy:
    name: Deploy to S3
    needs: security-scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Sync Files to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.S3_BUCKET_NAME }} --delete
        
      - name: Deployment Status
        run: |
          echo "Deployment completed successfully!"

